"""Publish built bundles to the `data` branch and redeploy the site.

    python -m pitwall.export          # build new sessions into ../data
    python -m pitwall.publish         # push them and trigger the Pages workflow

F1's live-timing archive refuses requests from cloud hosts (GitHub Actions
included), so bundles are built on a normal connection and published from
there. The `data` branch holds only generated JSON and is rewritten as a
single commit each time, so the repository never accumulates old copies.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from . import config

BRANCH = "data"


def _git(*args: str, cwd: Path) -> str:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True,
                          text=True).stdout.strip()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--data", type=Path, default=config.DATA_DIR)
    ap.add_argument("--remote", default="origin")
    ap.add_argument("--no-deploy", action="store_true", help="push only, skip the workflow run")
    args = ap.parse_args(argv)

    data: Path = args.data.resolve()
    index = data / "index.json"
    if not index.exists():
        print(f"no index.json in {data}; run `python -m pitwall.export` first", file=sys.stderr)
        return 1
    sessions = sum(len(ev["built"]) for s in json.loads(index.read_text())["seasons"]
                   for ev in s["events"])

    remote = _git("remote", "get-url", args.remote, cwd=config.ROOT)
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    with tempfile.TemporaryDirectory(prefix="pitwall-publish-") as tmp:
        work = Path(tmp)
        shutil.copytree(data, work, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns("pitwall-*", ".git"))
        (work / "README.md").write_text(
            "Generated by `python -m pitwall.publish`. Do not edit: the branch is "
            "rewritten on every publish.\n",
            encoding="utf-8",
        )
        _git("init", "-q", "-b", BRANCH, cwd=work)
        _git("add", "-A", cwd=work)
        _git("commit", "-q", "-m", f"data: {sessions} sessions, built {stamp}", cwd=work)
        # Force: the branch is a single generated snapshot, see module docstring.
        _git("push", "-q", "--force", remote, f"{BRANCH}:{BRANCH}", cwd=work)
    print(f"published {sessions} sessions to {BRANCH}")

    if args.no_deploy:
        return 0
    if shutil.which("gh") is None:
        print("gh CLI not found: run the 'Deploy site' workflow from the Actions tab")
        return 0
    subprocess.run(["gh", "workflow", "run", "pages.yml", "--ref", "main"], cwd=config.ROOT,
                   check=True)
    print("triggered the Pages deploy")
    return 0


if __name__ == "__main__":
    sys.exit(main())
